----
spring :
   profiles : dev
server:
  port:  3301
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761:8761/eureka
  ---
spring :
   profiles : test
server:
  port:  3301
eureka:
  client:
    service-url:
      defaultZone: http://eureka8762:8762/eureka